# .streamlit/secrets.toml

public_sheet_url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRkn_uS7XLMvSK3pW0f8QIAVgoT0Lj3U_O-3VkMTgW6ATZtYILU30t7Fih5lj28uZcWjk3CzKu2iFat/pub?gid=710960365&single=true&output=csv"
transactions_sheet_url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQhRWwptwEAica4po2XhPLn1e73t05UpK-waUFj3fkv9oL9drgDJEyVf2G2WCdB6GzHOYFNbutzPLF0/pub?gid=1713409441&single=true&output=csv"
trading_journal_url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRkn_uS7XLMvSK3pW0f8QIAVgoT0Lj3U_O-3VkMTgW6ATZtYILU30t7Fih5lj28uZcWjk3CzKu2iFat/pub?gid=806816365&single=true&output=csv"
app_password = "BenjoBerry99"