# .streamlit/secrets.toml

public_sheet_url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRkn_uS7XLMvSK3pW0f8QIAVgoT0Lj3U_O-3VkMTgW6ATZtYILU30t7Fih5lj28uZcWjk3CzKu2iFat/pub?gid=710960365&single=true&output=csv"
app_password = "BenjoBerry99"